### ISSUE TITLE
ng build ERROR

### ISSUE THREAD

**Issue by smile2014** [hdjirdeh/angular2-hn#14]
ERROR in [default] e:\learning\angular2\Angular2-HNews-master\src\app\stories\stories.component.ts:31:49                 
Property 'storiesType' does not exist on type '{ [name: string]: any; }'.                                                
                                                                                                                         
ERROR in [default] e:\learning\angular2\Angular2-HNews-master\src\app\user\user.component.ts:25:33                       
Property 'fetchUser' does not exist on type 'HackerNewsAPIService'.

**Comment by hdjirdeh** [comment]
Thank you for filing this!

`Property 'storiesType' does not exist on type '{ [name: string]: any; }'` is just because the compiler can't find a `storiesType` parameter on the object. A quick fix is just to assign type `any` to the response object to opt-out of type checking. I updated my code with this fix a short while ago:

    ngOnInit() {
      this.typeSub = this.route
       .data
        .subscribe(data => this.storiesType = (data as any).storiesType);

    // ...
    }

`Property 'fetchUser' does not exist on type 'HackerNewsAPIService'`. Hmm where are you seeing this issue? The `fetchUser` method should be in the data service whenever it's being called so just double check and see if you might have forgotten to add it.

**Comment by hdjirdeh** [comment]
@smile2014 Going to close this, but please let me know if you're still seeing issues
