### ISSUE TITLE
Support for polls

### ISSUE THREAD

**Issue by hdjirdeh** [hdjirdeh/angular2-hn#2]
So this doesn't yet support polls:

Hackernews: https://news.ycombinator.com/item?id=7059569
Angular2HN: https://angular2-hn.firebaseapp.com/item/7059569

This isn't complicated at all. In the *item.comments.component* you'll just need to do a check for type === poll and if so, get the details from the poll object in the response.

![image](https://cloud.githubusercontent.com/assets/12476932/18369252/a4e875d4-75f2-11e6-8fe8-185a1ee7911d.png)

It would be nice to have bars to represent the results as well, but maybe we can just start with outputting the results and then doing that later.

**Comment by mateuszwitkowski** [comment]
I've started working on this but there's no named options for polls in response, just numbers. So there's no way to explain what they mean. Is there a way to fetch options (answers)?

**Comment by hdjirdeh** [comment]
Thanks for looking into this! Hmm surprised I didn't notice that.

Okay I guess we can use the [official API](https://github.com/HackerNews/API/blob/master/README.md) for this. Unfortunately that means we'll have to fire another request to get the item details using this API and then fire a separate request for each of the 'poll parts', but I think I'm okay with that for now. We can do this for now until we find a better solution or another unofficial API that could do it in an easier way.

Don't hesitate to ask if you have any questions at all mate.

**Comment by mateuszwitkowski** [comment]
I'm preparing PR now. I've stumbled upon some issues along the road but I think I've handled it. One thing I should mention: each of the 'poll parts' has field named 'content'. Turned out that it's a HTML converted to a string, i.e. `content
:
"<p>&gt;$150,000&#x2F;year"`. For that reason I needed to use attribute binding ( [innerHTML] ) to get things working. I don't like it though since  one never knows what kind of HTML it's gonna be. I've been working with Angular 2 for ~1 month (in fact I've started my adventure with "professional programming" a month ago and six months ago I didn't know anything about programming at all), so if there's any mistakes or bad practices in my code I would be grateful for pointing them out. If logic will be OK I'll work on some kind of nice outputs (maybe mini-charts). Now it's just plain text (but consistent with the overall design).

**Comment by hdjirdeh** [comment]
Wow this is fantastic! You did a solid job it outputs the polls perfectly. And this is amazing work for only a month into Angular and less then 2 months into professional programming.

I didn't realize the the consecutive item id's return the poll details in the API, so that's a good find 👍. Saves us the trouble from using a separate API to do this.

I put a few comments in the PR for some minor changes, let's shift the discussion there..
